name: PR Check before deployment
on:
  pull_request:
#    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  deploy:
    name: Test Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true

      - name: Install dependencies
        #run: npm ci
        run: npm test

      - name: Build and Publish to Oxygen
        run: echo "npx shopify hydrogen deploy"
        env:
          SHOPIFY_HYDROGEN_DEPLOYMENT_TOKEN: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_temptemp }}